const STORE_KEY = 'POKEMON';

export const FETCH_SUGGESTIONS_REQUEST = `${STORE_KEY}/FETCH_SUGGESTIONS_REQUEST`;
export const FETCH_SUGGESTIONS_SUCCESS = `${STORE_KEY}/FETCH_SUGGESTIONS_SUCCESS`;
export const FETCH_SUGGESTIONS_ERROR = `${STORE_KEY}/FETCH_SUGGESTIONS_ERROR`;

export const FETCH_POKEMON_REQUEST = `${STORE_KEY}/FETCH_POKEMON_REQUEST`;
export const FETCH_POKEMON_SUCCESS = `${STORE_KEY}/FETCH_POKEMON_SUCCESS`;
export const FETCH_POKEMON_ERROR = `${STORE_KEY}/FETCH_POKEMON_FAILURE`;
export const REMOVE_POKEMON = `${STORE_KEY}/REMOVE_POKEMON`;
